# Generated by Django 5.2.4 on 2025-08-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_sub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='AuUser',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='CP',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='CU',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post_category',
            old_name='MC',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post_category',
            old_name='MP',
            new_name='post',
        ),
    ]
