# Generated by Django 5.2.4 on 2025-08-11 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_auuser_author_name_rename_cp_comment_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_es',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_es',
            field=models.CharField(max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
